"""empty message

Revision ID: 7cd1ffe1f102
Revises: 1a3449d20d04
Create Date: 2023-03-05 10:37:52.068416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cd1ffe1f102"
down_revision = "1a3449d20d04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mutual_fund",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("market", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("mutualfunds")
    op.drop_table("cryptos")
    op.drop_table("stocks")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("chat_id", sa.INTEGER(), nullable=True),
        sa.Column("symbol", sa.VARCHAR(), nullable=True),
        sa.Column("quantity", sa.INTEGER(), nullable=True),
        sa.Column("market", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cryptos",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("chat_id", sa.INTEGER(), nullable=True),
        sa.Column("symbol", sa.VARCHAR(), nullable=True),
        sa.Column("quantity", sa.FLOAT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mutualfunds",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("chat_id", sa.INTEGER(), nullable=True),
        sa.Column("symbol", sa.VARCHAR(), nullable=True),
        sa.Column("quantity", sa.FLOAT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("stock")
    op.drop_table("mutual_fund")
    op.drop_table("crypto")
    # ### end Alembic commands ###
